### ISSUE TITLE
WSS connection sertificate validation

### ISSUE THREAD

**Issue by agiUnderground** [tfausak/wuss#12]
Hello! I'm trying to connect to the wss:// , and provide ip as a host name, but get the following error:

HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"127.0.0.1\"]",True,CertificateUnknown))

How I can provide my .crt certificate to the program?

`wuss-1.1.9`

**Comment by tfausak** [comment]
Certificates are handled at the TLS level. I don't know off the top of my head how to provide certs to the TLS lib, but [this example](https://www.stackage.org/haddock/lts-11.13/wuss-1.1.9/Wuss.html#v:runSecureClientWith) in the docs might be a good place to start.

**Comment by agiUnderground** [comment]
ok, thank you anyway.

**Comment by tfausak** [comment]
I'm going to close this, but please re-open it if anything about Wuss needs to change to accommodate this.
