### ISSUE TITLE
Cannot Build with GHC 8.6.1

### ISSUE THREAD

**Issue by iamrecursion** [tfausak/wuss#13]
The version bounds on `base` are too limiting to support GHC-8.6.1. I'd really appreciate if you're able to bump the bounds soon!

**Comment by tfausak** [comment]
I'd be happy to update the bounds! I hadn't done so yet because last time I tried, some of Wuss's dependencies didn't work with 8.6.1 either. I'll try again soon.

**Comment by iamrecursion** [comment]
Brilliant, thanks for the update! Hopefully the dependencies get themselves in order quick smart!

**Comment by tfausak** [comment]
Should be fixed by 5414701178824cfa706db9553a3584ae0280b8fd. Thanks for reporting!

**Comment by iamrecursion** [comment]
Thanks so much for getting this sorted!
