### ISSUE TITLE
Bump upper bound on base for GHC 8.8.1 compatibility

### ISSUE THREAD

**Issue by dbaynard** [tfausak/wuss#15]
Would you kindly add a hackage revision allowing [`base-4.13.0.0`](https://gitlab.haskell.org/ghc/ghc/wikis/commentary/libraries/version-history) (annoyingly that version has not yet been released on hackage)?

I've tested `wuss` in an application which uses it; it works fine.

**Comment by tfausak** [comment]
Thanks for the ping! Should be released as version 1.1.15 just as soon as CI finishes building it.
