### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by hazel-web** [tfausak/wuss#16]
cabal install wuss    
Resolving dependencies...                                                                                               
Build profile: -w ghc-8.10.2 -O1             
Failed to build zlib-0.6.2.2.
Preprocessing library for zlib-0.6.2.2..
Building library for zlib-0.6.2.2..
[1 of 5] Compiling Codec.Compression.Zlib.Stream ( dist\build\Codec\Compression\Zlib\Stream.hs, dist\build\Codec\Compression\Zlib\Stream.o )
ghc.exe: could not execute: C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe
cabal.exe: Failed to build zlib-0.6.2.2 (which is required by wuss-1.1.17).

**Comment by tfausak** [comment]
It looks like you're on Windows and it's failing to install [the `zlib` package](https://hackage.haskell.org/package/zlib-0.6.2.2). I think this is the upstream issue: https://github.com/haskell/zlib/issues/35. That ends up linking to this GHC issue: https://gitlab.haskell.org/ghc/ghc/-/issues/18550

As a workaround I think you could try using a different version of GHC (8.10.1 or 8.8.3).

**Comment by tfausak** [comment]
I'm going to close this because it doesn't appear to be a problem with Wuss itself.
