### ISSUE TITLE
Retry HTTP request

### ISSUE THREAD

**Issue by domenkozar** [tfausak/wuss#18]
Currently if the client can't connect it will just hang (in case of 404).

A better default would be to retry http requests and possibly offer a way to override that default.

**Comment by tfausak** [comment]
Would it suffice to expose a version of `runSecureClientWithConfig` that takes the established connection as an argument? That way the user could decide how they want to connect if it's important to them.

**Comment by domenkozar** [comment]
Something like `Request -> IO Http.Response`?

In that case, the implementation would be making the HTTP request?

**Comment by tfausak** [comment]
I meant something that allowed customizing these lines:

https://github.com/tfausak/wuss/blob/da6c60f00f4d37d0e40a2240a232144356cb3a05/src/lib/Wuss.hs#L162-L163

Wuss itself doesn't make any requests other than the initial connection.

**Comment by tfausak** [comment]
I'm curious if this is something that Wuss can or should support. Perhaps the functionality should be added to the `connection` or `network` library? Or perhaps the application can manage timeouts? I'm not really sure how to move forward with this issue.

**Comment by domenkozar** [comment]
I think it doesn't have to be offered by wuss, but it's a crucial component for having websockets work, so it should be at the very least documented what the user is expected to implement.

I used `retry` package:

```haskell

retryAllWithLogging :: (MonadIO m, MonadMask m) => RetryPolicyM m -> (Bool -> SomeException -> RetryStatus -> m ()) -> m a -> m a
retryAllWithLogging retryPolicy logger action = recovering retryPolicy handlers $ const action
  where
    handlers = skipAsyncExceptions ++ [loggingHandler]

    loggingHandler = logRetries exceptionPredicate logger

    exceptionPredicate = return . isSyncException
```
