### ISSUE TITLE
Expose `newSecureClientConnection`

### ISSUE THREAD

**Issue by sandydoo** [tfausak/wuss#22]
`websockets` provides [`newClientConnection`](https://hackage.haskell.org/package/websockets-0.12.7.3/docs/Network-WebSockets.html#v:newClientConnection) as an alternative to the bracket-style functions. It allows the app to take responsibility for managing/cleaning up the connection by separating the connection and the `clientApp`. I’m proposing we add the corresponding secure version:

```haskell
newSecureClientConnection
	:: Socket.Host -- ^ Host
	-> Socket.PortNumber -- ^ Port
	-> String.String -- ^ Path
    -> Config -- ^ Config
    -> WebSockets.ConnectionOptions -- ^ Options
    -> WebSockets.Headers -- ^ Headers
    -> IO.IO (WebSockets.Connection)
```

#### Timeout

Currently, the initial connection will hang indefinitely if the server is unresponsive. With `newSecureClientConnection`, we can add a timeout just for the connection and handshake.

```haskell
import qualified System.Timeout as Timeout

maybeConnection <- Timeout.timeout 5_000_000 $ newSecureClientConnection ...
```

Related issues:
https://github.com/jaspervdj/websockets/issues/229

#### Retry

The `retry` package doesn’t play well with websockets. The retry counter is designed to reset when the inner function returns, but a websocket doesn’t return once successfully connected. For example, if you use exponential backoff, the backoff will keep increasing every time the connection drops, even with successful connections in between.
With `newSecureClientConnection`, we can at least handle an unresponsive server by wrapping the connection in a retry. Errors from the `clientApp` would have to be handled separately.

Related issues:
https://github.com/Soostone/retry/issues/25
https://github.com/tfausak/wuss/issues/18

### Alternatives

The alternative would be to manage the connection manually, without Wuss.

Would there be interest in adding this? Any thoughts?

**Comment by tfausak** [comment]
Sure, I think that makes sense to add. I'd accept a PR for it.

**Comment by tfausak** [comment]
Realistically I'm not going to get around to doing this.

**Comment by domenkozar** [comment]
If anyone hits this issue: we created [Stamina](https://hackage.haskell.org/package/stamina-0.1.0.2/docs/Stamina.html#t:RetryStatus) that allows you to reset the retrying state and [typed-websockets](https://github.com/cachix/typed-websockets) use it for the client side to indefinitely reconnect.
