### ISSUE TITLE
Extending to also cover the server side

### ISSUE THREAD

**Issue by deepfire** [tfausak/wuss#30]
Has there been any consideration for extending this to also cover the server side?

I've sketched something working, but that failed to start any upstream discussion at all:

https://github.com/jaspervdj/websockets/pull/215

**Comment by tfausak** [comment]
No, not really. This package is basically in maintenance mode for me.

**Comment by deepfire** [comment]
I see -- would you be at least theoretically open to consider accepting such an implementation, if it was provided?

**Comment by tfausak** [comment]
Perhaps, but it depends on the size and complexity. There isn't really that much to this library. I'd suggest making a separate package to support WSS servers.

**Comment by tfausak** [comment]
Realistically I'm not going to get around to doing this.
