### ISSUE TITLE
Put on Stackage

### ISSUE THREAD

**Issue by barrucadu** [tfausak/wuss#4]
It would be convenient for this to be on Stackage, the process is pretty simple: https://github.com/fpco/stackage/blob/master/MAINTAINERS.md

**Comment by tfausak** [comment]
:point_right: https://github.com/fpco/stackage/pull/1275

**Comment by tfausak** [comment]
Wuss should be in the next nightly snapshot. Thanks!

**Comment by tfausak** [comment]
Wuss is included with [nightly-2016-03-15](https://www.stackage.org/diff/nightly-2016-03-14/nightly-2016-03-15).
