### ISSUE TITLE
Option for connectionGetLine instead of connectionGetChunk

### ISSUE THREAD

**Issue by Shou** [tfausak/wuss#5]
I believe `connectionGetLine` is the way `Network.WebSockets` does it by default, but I could be wrong.

**Comment by tfausak** [comment]
What's the motivation here? When is `connectionGetChunk` inappropriate?

**Comment by Shou** [comment]
When lines are needed promptly, e.g. in a chat program.

**Comment by tfausak** [comment]
Fair enough. How would you like this option to be exposed?

**Comment by Shou** [comment]
Maybe something like an exposed WussOptions data object. This should be easy to expand later on if needed.

```haskell
data GetMode = GetBytes Int | GetChunk | GetLine Int
data WussOptions = WussOptions { connGetMode :: GetMode }
```
